# Generated by Django 4.2.7 on 2024-12-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
