# Generated by Django 4.2.7 on 2024-12-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
