# Generated by Django 4.2.7 on 2024-12-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='roll_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
