# Generated by Django 4.2.7 on 2024-12-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_course_roll_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Only applicable for teachers', related_name='teachers', to='Auth.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='lec',
            field=models.BooleanField(default=False, help_text='Access to lectures'),
        ),
        migrations.AddField(
            model_name='user',
            name='live',
            field=models.BooleanField(default=False, help_text='Access to live sessions'),
        ),
        migrations.AddField(
            model_name='user',
            name='mat',
            field=models.BooleanField(default=False, help_text='Access to materials'),
        ),
        migrations.AddField(
            model_name='user',
            name='tests',
            field=models.BooleanField(default=False, help_text='Access to tests'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Only applicable for students', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Auth.course'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(help_text='The course to which this subject belongs', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Auth.course')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Applicable for teachers only', to='Auth.subject'),
        ),
    ]
