# Generated by Django 4.2.7 on 2024-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(default=0, help_text="User's contact number", max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
